# Generated by Django 5.1.4 on 2025-02-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['creation_time']},
        ),
        migrations.AlterModelOptions(
            name='printqueue',
            options={'ordering': ['creation_time']},
        ),
        migrations.AlterModelOptions(
            name='workplace',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ready_to_print', 'Ready to Print'), ('in_progress', 'In Progress'), ('problem', 'Problem'), ('done', 'Done')], default='ready_to_print', max_length=50),
        ),
        migrations.AddField(
            model_name='printer',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='printqueue',
            name='status',
            field=models.CharField(choices=[('ready_to_print', 'Ready to Print'), ('in_progress', 'In Progress'), ('problem', 'Problem'), ('done', 'Done')], default='ready_to_print', max_length=50),
        ),
    ]
