# Generated by Django 5.1.4 on 2024-12-12 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(code='invalid_number', message='Phone number must be entered in the format: <+3809999999>', regex='^\\+380\\d{9}$')]),
        ),
    ]
