# Generated by Django 5.1.4 on 2025-02-05 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_order_options_alter_printqueue_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
