# Generated by Django 5.1.4 on 2024-12-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_alter_worker_options_alter_worker_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('roll_width', models.FloatField()),
                ('winding', models.IntegerField()),
                ('density', models.IntegerField()),
            ],
            options={
                'ordering': ['type'],
            },
        ),
    ]
