# Generated by Django 5.1.4 on 2025-02-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[], default=('ready_to_print', 'Ready to Print'), max_length=50),
        ),
        migrations.AlterField(
            model_name='printqueue',
            name='status',
            field=models.CharField(choices=[], default=('ready_to_print', 'Ready to Print'), max_length=50),
        ),
    ]
