# Generated by Django 5.1.4 on 2025-02-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_alter_printqueue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printqueue',
            name='status',
            field=models.CharField(choices=[('ready_to_print', 'Ready to Print'), ('in_progress', 'In Progress'), ('done', 'Done'), ('problem', 'Problem')], default='ready_to_print', max_length=50),
        ),
    ]
