# Generated by Django 5.1.4 on 2025-02-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_alter_order_status_alter_printer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance')], default='active', max_length=20),
        ),
    ]
